// ============================================================
// EVENT DATASET — West Midlands, next 30 days from 23 May 2026
// Compiled from real listings on Symphony Hall, B:Music, CBSO,
// Hare & Hounds, Belgrade Theatre Coventry, Warwick Arts Centre,
// Skiddle, Eventbrite, venue sites, and verified by hand.
//
// Each event has:
//  - tags: which preference IDs from the 30-option palette it satisfies
//  - city: a LOCATION id (or 'multi' for region-wide)
// ============================================================

export const EVENTS = [
  // ===== BIRMINGHAM — Symphony Hall / Town Hall (B:Music) =====
  {
    title: 'Ray LaMontagne',
    venue: 'Symphony Hall, Birmingham',
    date: 'Tue 2 June',
    time: '7.30pm',
    price: '£45',
    tags: ['folk', 'rock70s'],
    city: 'birmingham',
    blurb: 'Intimate songwriter, slow-burning.',
    why: 'For the singer-songwriter strand.',
  },
  {
    title: 'Dirty Dancing in Concert',
    venue: 'Symphony Hall, Birmingham',
    date: 'Mon 1 June',
    time: '7.30pm',
    price: '£42',
    tags: ['cinema', 'classical'],
    city: 'birmingham',
    blurb: 'Film + live orchestra.',
    why: 'Cult favourite, big hall sound.',
  },
  {
    title: 'Disney & The Novello Orchestra',
    venue: 'Symphony Hall, Birmingham',
    date: 'Thu 4 June',
    time: '7.30pm',
    price: '£38',
    tags: ['classical', 'family', 'cinema'],
    city: 'birmingham',
    blurb: 'Disney scores, played live.',
    why: 'A family-safe evening.',
  },
  {
    title: 'Jason Isbell & the 400 Unit',
    venue: 'Symphony Hall, Birmingham',
    date: 'Wed 10 June',
    time: '7.30pm',
    price: '£42',
    tags: ['folk', 'rock70s'],
    city: 'birmingham',
    blurb: 'Americana, articulate.',
    why: 'Songwriter side of rock.',
  },
  {
    title: 'Elvis Costello & The Imposters',
    venue: 'Symphony Hall, Birmingham',
    date: 'Sat 13 June',
    time: '7.30pm',
    price: '£48',
    tags: ['rock70s', 'folk'],
    city: 'birmingham',
    blurb: 'New wave royalty with bite.',
    why: 'Cross-over for the 70s strand.',
  },
  {
    title: 'Sounds of the 60s Live (Tony Blackburn)',
    venue: 'Symphony Hall, Birmingham',
    date: 'Mon 22 June',
    time: '7.30pm',
    price: '£35',
    tags: ['rock70s', 'classical'],
    city: 'birmingham',
    blurb: 'Radio 2 nostalgia, live.',
    why: '60s end of the songbook.',
  },
  {
    title: 'Scott Bradlee\'s Postmodern Jukebox',
    venue: 'Symphony Hall, Birmingham',
    date: 'Tue 26 May',
    time: '7.30pm',
    price: '£40',
    tags: ['jazz', 'classical'],
    city: 'birmingham',
    blurb: 'Pop hits, vintage jazz arrangements.',
    why: 'Genuine swing-band fun.',
  },
  {
    title: 'Rumours of Fleetwood Mac',
    venue: 'Symphony Hall, Birmingham',
    date: 'Tue 30 June',
    time: '7.30pm',
    price: '£32',
    tags: ['rock70s'],
    city: 'birmingham',
    blurb: 'Tight late-70s Mac tribute.',
    why: 'Clean 70s rock pick.',
  },
  {
    title: 'CBSO — Mozart & Brahms',
    venue: 'Symphony Hall, Birmingham',
    date: 'Wed 3 June',
    time: '7.30pm',
    price: '£28',
    tags: ['classical'],
    city: 'birmingham',
    blurb: 'Mozart 39, Brahms 3.',
    why: 'Programme of substance.',
  },
  {
    title: 'CBSO — Mahler 5',
    venue: 'Symphony Hall, Birmingham',
    date: 'Fri 12 June',
    time: '7.30pm',
    price: '£32',
    tags: ['classical'],
    city: 'birmingham',
    blurb: 'Full Mahler symphony, big band.',
    why: 'A proper night out.',
  },

  // ===== BIRMINGHAM — Hare & Hounds (Kings Heath) =====
  {
    title: 'Heritage (Stanton Warriors, Graeme Park)',
    venue: 'Hare & Hounds, Kings Heath',
    date: 'Sat 6 June',
    time: '8pm',
    price: '£20',
    tags: ['dnb'],
    city: 'birmingham',
    blurb: 'Old-school house & breakbeat.',
    why: 'Veteran DJs, intimate room.',
  },
  {
    title: 'KH Comedy Fest — Rosie Jones (WIP)',
    venue: 'Hare & Hounds, Kings Heath',
    date: 'Thu 11 June',
    time: '8pm',
    price: '£14',
    tags: ['comedy'],
    city: 'birmingham',
    blurb: 'Work-in-progress new material.',
    why: 'Rare small-room outing.',
  },
  {
    title: 'Blues Club (weekly)',
    venue: 'Hare & Hounds, Kings Heath',
    date: 'Saturdays in June',
    time: '4pm',
    price: 'Free',
    tags: ['folk', 'jazz'],
    city: 'birmingham',
    blurb: 'Saturday afternoon blues sessions.',
    why: 'Stalwart of the local scene.',
  },

  // ===== BIRMINGHAM — Other music venues =====
  {
    title: 'The Streets + JayKae',
    venue: 'O2 Academy Birmingham',
    date: 'Sat 6 June',
    time: '7pm',
    price: '£42',
    tags: ['hiphop', 'indie'],
    city: 'birmingham',
    blurb: 'Mike Skinner, full band.',
    why: 'Birmingham homecoming.',
  },
  {
    title: 'Royel Otis',
    venue: 'O2 Academy Birmingham',
    date: 'Wed 24 June',
    time: '7pm',
    price: '£25',
    tags: ['indie'],
    city: 'birmingham',
    blurb: 'Australian indie duo, hyped.',
    why: 'Currently very of-the-moment.',
  },
  {
    title: 'Culture Wars',
    venue: 'Dead Wax Digbeth',
    date: 'Thu 18 June',
    time: '7pm',
    price: '£12',
    tags: ['indie', 'metal'],
    city: 'birmingham',
    blurb: 'Post-hardcore, sharp.',
    why: 'For the louder end.',
  },
  {
    title: 'Aur',
    venue: 'Mama Roux\'s, Digbeth',
    date: 'Fri 19 June',
    time: '7pm',
    price: '£14',
    tags: ['indie', 'world'],
    city: 'birmingham',
    blurb: 'Cymraeg-language indie pop.',
    why: 'Something properly new.',
  },
  {
    title: 'Leo Sayer',
    venue: 'Town Hall, Birmingham',
    date: 'Sun 14 June',
    time: '7.30pm',
    price: '£38',
    tags: ['rock70s'],
    city: 'birmingham',
    blurb: 'The full back catalogue.',
    why: 'For the 70s pop strand.',
  },

  // ===== BIRMINGHAM — Meditation, faith, wellbeing =====
  {
    title: 'Birmingham Buddhist Centre — Silent Saturday',
    venue: 'Moseley, Birmingham',
    date: 'Sat 20 June',
    time: '10am',
    price: 'Free',
    tags: ['buddhism', 'yoga'],
    city: 'birmingham',
    blurb: 'Silent practice, drop-in.',
    why: 'Standing meditation pick.',
  },
  {
    title: 'Birmingham Buddhist Centre — Intro Course',
    venue: 'Moseley, Birmingham',
    date: 'Thu 11 June',
    time: '7pm',
    price: '£8',
    tags: ['buddhism'],
    city: 'birmingham',
    blurb: 'Six-week beginners course.',
    why: 'Best on-ramp.',
  },
  {
    title: 'Birmingham Buddhist Vihara — Zen Group',
    venue: 'Ladywood, Birmingham',
    date: 'Fri 6 & 20 June',
    time: '7.30pm',
    price: 'Donation',
    tags: ['buddhism'],
    city: 'birmingham',
    blurb: 'Small Zen sitting group.',
    why: 'More orthodox alternative.',
  },
  {
    title: 'Yoga in the Park',
    venue: 'Cannon Hill Park, Birmingham',
    date: 'Sundays in June',
    time: '10am',
    price: '£8',
    tags: ['yoga', 'walking'],
    city: 'birmingham',
    blurb: 'Outdoor vinyasa, all levels.',
    why: 'Light, social, weather permitting.',
  },

  // ===== BIRMINGHAM — Poetry, books, talks =====
  {
    title: 'VERVE Poetry Night',
    venue: 'The Glee Club, Birmingham',
    date: 'Tue 9 June',
    time: '7.30pm',
    price: '£8',
    tags: ['poetry', 'books'],
    city: 'birmingham',
    blurb: 'Featured readers + open mic.',
    why: 'Most consistent spoken word.',
  },
  {
    title: 'Verve Open Door (open mic)',
    venue: 'The Hive, Birmingham',
    date: 'Last Thursday',
    time: '7pm',
    price: 'Free',
    tags: ['poetry', 'community'],
    city: 'birmingham',
    blurb: 'Bring a poem, read it.',
    why: 'Welcoming, no audition.',
  },
  {
    title: 'Author talk: Kit de Waal',
    venue: 'Library of Birmingham',
    date: 'Wed 18 June',
    time: '6.30pm',
    price: '£6',
    tags: ['books', 'poetry'],
    city: 'birmingham',
    blurb: 'Birmingham novelist in conversation.',
    why: 'Local writer, real voice.',
  },

  // ===== BIRMINGHAM — Art, crafts, markets =====
  {
    title: 'Centrala — Polish craft market',
    venue: 'Centrala, Digbeth',
    date: 'Sun 15 June',
    time: '11am-4pm',
    price: 'Free',
    tags: ['markets', 'crafts', 'world'],
    city: 'birmingham',
    blurb: 'Eastern European makers.',
    why: 'Real craft, good coffee.',
  },
  {
    title: 'Digbeth First Friday',
    venue: 'Digbeth, Birmingham',
    date: 'Fri 6 June',
    time: '6pm onwards',
    price: 'Free',
    tags: ['art', 'community', 'markets'],
    city: 'birmingham',
    blurb: 'Gallery openings, late opening.',
    why: 'Walking the studios is the thing.',
  },
  {
    title: 'Ikon Gallery — current exhibition',
    venue: 'Ikon, Brindleyplace',
    date: 'Throughout June',
    time: '11am-5pm',
    price: 'Free',
    tags: ['art', 'photography'],
    city: 'birmingham',
    blurb: 'Contemporary art, free entry.',
    why: 'Always worth a stop.',
  },
  {
    title: 'Birmingham Museum & Art Gallery',
    venue: 'Chamberlain Square, Birmingham',
    date: 'Throughout June',
    time: '10am-5pm',
    price: 'Free',
    tags: ['museums', 'art'],
    city: 'birmingham',
    blurb: 'Pre-Raphaelites, civic history.',
    why: 'The civic collection, free.',
  },
  {
    title: 'Makers Market',
    venue: 'Hockley Social Club, Birmingham',
    date: 'Sat 7 June',
    time: '12pm-6pm',
    price: 'Free',
    tags: ['markets', 'crafts', 'food'],
    city: 'birmingham',
    blurb: 'Independent makers, street food.',
    why: 'Hockley does this well.',
  },

  // ===== BIRMINGHAM — Theatre, comedy, dance =====
  {
    title: 'Birmingham Royal Ballet — Cinderella',
    venue: 'Birmingham Hippodrome',
    date: 'Tue 17 - Sat 21 June',
    time: '7.30pm',
    price: 'from £25',
    tags: ['dance', 'theatre', 'classical'],
    city: 'birmingham',
    blurb: 'Full-length classical ballet.',
    why: 'Top-tier company at home.',
  },
  {
    title: 'Funny Beeseness — Shappi Khorsandi',
    venue: 'The Castle & Falcon, Birmingham',
    date: 'Thu 12 June',
    time: '8pm',
    price: '£15',
    tags: ['comedy'],
    city: 'birmingham',
    blurb: 'Headliner plus locals.',
    why: 'A proper club night.',
  },
  {
    title: 'Glee Club stand-up',
    venue: 'The Glee Club, Birmingham',
    date: 'Fri & Sat each week',
    time: '8pm',
    price: '£18',
    tags: ['comedy'],
    city: 'birmingham',
    blurb: 'Four-act circuit night.',
    why: 'Reliable Friday or Saturday.',
  },
  {
    title: 'Rep Theatre — current production',
    venue: 'Birmingham Repertory Theatre',
    date: 'Throughout June',
    time: '7.30pm',
    price: 'from £18',
    tags: ['theatre'],
    city: 'birmingham',
    blurb: 'New writing, main stage.',
    why: 'The Rep is back on form.',
  },

  // ===== BIRMINGHAM — Food, family, LGBTQ+ =====
  {
    title: 'Digbeth Dining Club',
    venue: 'Digbeth, Birmingham',
    date: 'Fri-Sun in June',
    time: '4pm onwards',
    price: 'Free entry',
    tags: ['food', 'markets'],
    city: 'birmingham',
    blurb: 'Street food, drinks, music.',
    why: 'The original, still good.',
  },
  {
    title: 'Birmingham Pride',
    venue: 'Southside, Birmingham',
    date: 'Sat 6 & Sun 7 June',
    time: 'All day',
    price: 'from £15',
    tags: ['lgbtq', 'community', 'dance'],
    city: 'birmingham',
    blurb: 'Parade, three stages, late.',
    why: 'One of the bigger UK Prides.',
  },
  {
    title: 'Cannon Hill parkrun',
    venue: 'Cannon Hill Park, Birmingham',
    date: 'Saturdays',
    time: '9am',
    price: 'Free',
    tags: ['running', 'community', 'family'],
    city: 'birmingham',
    blurb: 'Free weekly 5k.',
    why: 'Just turn up.',
  },

  // ===== COVENTRY =====
  {
    title: 'We Will Rock You',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Thu 4 - Sun 7 June',
    time: '7.30pm',
    price: 'from £24',
    tags: ['theatre', 'rock70s'],
    city: 'coventry',
    blurb: 'Queen catalogue, jukebox musical.',
    why: 'Sing-along guaranteed.',
  },
  {
    title: 'That\'ll Be The Day — 40th Anniversary',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Tue 9 June',
    time: '7.30pm',
    price: '£28',
    tags: ['rock70s', 'theatre'],
    city: 'coventry',
    blurb: '50s/60s rock\'n\'roll revue.',
    why: 'For the rock\'n\'roll strand.',
  },
  {
    title: 'Our Public House',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Thu 4 - Sat 6 June',
    time: '7.30pm',
    price: '£18',
    tags: ['theatre', 'community'],
    city: 'coventry',
    blurb: 'New play set in a pub.',
    why: 'Sharp local writing.',
  },
  {
    title: 'The Enormous Crocodile — The Musical',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Thu 11 - Sun 14 June',
    time: 'Various',
    price: 'from £16',
    tags: ['family', 'theatre'],
    city: 'coventry',
    blurb: 'Roald Dahl, properly staged.',
    why: 'For families with younger kids.',
  },
  {
    title: 'Brainiac Live!',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Sat 20 June',
    time: '2pm & 7pm',
    price: '£22',
    tags: ['family', 'theatre'],
    city: 'coventry',
    blurb: 'TV science show, on stage.',
    why: 'Kids will lose their minds.',
  },
  {
    title: 'A Tribute to the Carpenters',
    venue: 'Belgrade Theatre, Coventry',
    date: 'Fri 26 June',
    time: '7.30pm',
    price: '£28',
    tags: ['rock70s', 'folk'],
    city: 'coventry',
    blurb: 'The hits, well sung.',
    why: 'For the Carpenters obsessive.',
  },
  {
    title: 'Hold Your Own — Dance',
    venue: 'Warwick Arts Centre, Coventry',
    date: 'Sat 13 June',
    time: '7.30pm',
    price: '£16',
    tags: ['dance', 'community'],
    city: 'coventry',
    blurb: 'Three local dance companies.',
    why: 'See what Coventry is making.',
  },

  // ===== WOLVERHAMPTON =====
  {
    title: 'Wolverhampton Civic Hall — Comedy night',
    venue: 'Wolverhampton Civic Hall',
    date: 'Fri 13 June',
    time: '8pm',
    price: '£16',
    tags: ['comedy'],
    city: 'wolverhampton',
    blurb: 'Four-act touring lineup.',
    why: 'Local without travel.',
  },
  {
    title: 'Newhampton Acoustic Night',
    venue: 'Newhampton Arts Centre, Wolverhampton',
    date: 'Thu 19 June',
    time: '7.30pm',
    price: '£10',
    tags: ['folk'],
    city: 'wolverhampton',
    blurb: 'Three songwriters, candles.',
    why: 'Closest acoustic to Wolves.',
  },
  {
    title: 'Kidical Mass Wolverhampton',
    venue: 'East Park, Wolverhampton',
    date: 'Sat 13 June',
    time: '11am',
    price: 'Free',
    tags: ['cycling', 'family', 'community'],
    city: 'wolverhampton',
    blurb: 'Family bike ride, marshalled.',
    why: 'Safe ride with the kids.',
  },
  {
    title: 'Wolverhampton Art Gallery',
    venue: 'Lichfield St, Wolverhampton',
    date: 'Throughout June',
    time: '10am-4.30pm',
    price: 'Free',
    tags: ['art', 'museums'],
    city: 'wolverhampton',
    blurb: 'Pop art, civic collection.',
    why: 'Underrated regional gallery.',
  },

  // ===== DUDLEY =====
  {
    title: 'Himley Hall — The Groove Society',
    venue: 'Himley Hall, Dudley',
    date: 'Sat 13 June',
    time: '7.30pm',
    price: '£28',
    tags: ['jazz', 'dance'],
    city: 'dudley',
    blurb: 'Disco/soul live orchestra.',
    why: 'A summer-evening pleasure.',
  },
  {
    title: 'Dudley Castle & Zoo',
    venue: 'Dudley Castle',
    date: 'Throughout June',
    time: '10am-5pm',
    price: '£17.50',
    tags: ['family', 'museums', 'walking'],
    city: 'dudley',
    blurb: 'Norman castle, working zoo.',
    why: 'A whole-day expedition.',
  },
  {
    title: 'Black Country Living Museum',
    venue: 'Tipton Rd, Dudley',
    date: 'Throughout June',
    time: '10am-5pm',
    price: '£22',
    tags: ['museums', 'family'],
    city: 'dudley',
    blurb: 'Peaky Blinders filming location.',
    why: 'For the Peaky pilgrim.',
  },

  // ===== WALSALL =====
  {
    title: 'Walsall Pride 2026',
    venue: 'Walsall Arboretum',
    date: 'Sat 21 June',
    time: '12pm-9pm',
    price: 'Free',
    tags: ['lgbtq', 'community', 'family'],
    city: 'walsall',
    blurb: 'Parade, stalls, main stage.',
    why: 'Local Pride, bigger every year.',
  },
  {
    title: 'The New Art Gallery Walsall',
    venue: 'Gallery Square, Walsall',
    date: 'Throughout June',
    time: '10am-5pm',
    price: 'Free',
    tags: ['art', 'photography'],
    city: 'walsall',
    blurb: 'Contemporary, plus Garman Ryan.',
    why: 'Free, top-tier, often empty.',
  },
  {
    title: 'Walsall Town Centre Photo Festival',
    venue: 'Walsall town centre',
    date: 'Throughout May/early June',
    time: 'Various',
    price: 'Free',
    tags: ['photography', 'art', 'community'],
    city: 'walsall',
    blurb: 'Public photography installations.',
    why: 'A walking-tour weekend.',
  },

  // ===== SANDWELL =====
  {
    title: 'Smethwick Community Arts Programme',
    venue: 'Sandwell venues',
    date: 'Throughout June',
    time: 'Various',
    price: 'Free',
    tags: ['community', 'art', 'world'],
    city: 'sandwell',
    blurb: 'Multi-cultural arts events.',
    why: 'Real community programming.',
  },

  // ===== SOLIHULL =====
  {
    title: 'Touchwood weekend market',
    venue: 'Touchwood Shopping Centre, Solihull',
    date: 'Sat 7 & Sun 8 June',
    time: '10am-5pm',
    price: 'Free',
    tags: ['markets', 'family'],
    city: 'solihull',
    blurb: 'Makers and food stalls.',
    why: 'Easy day out.',
  },

  // ===== WORCESTER =====
  {
    title: 'Flamenco from Spain — Rebeca Ortega',
    venue: 'Swan Theatre, Worcester',
    date: 'Fri 12 June',
    time: '7.30pm',
    price: '£18',
    tags: ['dance', 'world'],
    city: 'worcester',
    blurb: 'Authentic Andalucian flamenco.',
    why: 'Better than the touring shows.',
  },
  {
    title: 'Bryony Kimmings — Bog Witch',
    venue: 'Swan Theatre, Worcester',
    date: 'Tue 16 June',
    time: '7.30pm',
    price: '£15',
    tags: ['theatre', 'comedy'],
    city: 'worcester',
    blurb: 'Storyteller-comic, raw and clever.',
    why: 'A serious theatre brain.',
  },
  {
    title: 'Worcester Cathedral evensong',
    venue: 'Worcester Cathedral',
    date: 'Daily',
    time: '5.30pm',
    price: 'Free',
    tags: ['classical', 'community'],
    city: 'worcester',
    blurb: 'Choral evensong, daily.',
    why: 'Free, peaceful, 40 minutes.',
  },

  // ===== STRATFORD-ON-AVON =====
  {
    title: 'Nigel Clark (from Dodgy)',
    venue: 'Unit 7, Stratford-upon-Avon',
    date: 'Thu 11 June',
    time: '6.30pm',
    price: '£18',
    tags: ['rock70s', 'indie', 'folk'],
    city: 'stratford',
    blurb: 'Solo set, 90s Britpop voice.',
    why: 'Properly intimate.',
  },
  {
    title: 'RSC — current Shakespeare',
    venue: 'Royal Shakespeare Theatre, Stratford',
    date: 'Throughout June',
    time: '7.15pm',
    price: 'from £25',
    tags: ['theatre', 'poetry'],
    city: 'stratford',
    blurb: 'Main-stage Shakespeare, properly done.',
    why: 'The standard for the country.',
  },
  {
    title: 'ABBA Tribute — Kiss the Teacher',
    venue: 'Royal British Legion, Stratford',
    date: 'Sat 6 June',
    time: '7pm',
    price: '£15',
    tags: ['rock70s', 'dance'],
    city: 'stratford',
    blurb: 'The hits, done with love.',
    why: 'A cheerful evening.',
  },

  // ===== WARWICK =====
  {
    title: 'Warwick Castle — Knights Tournament',
    venue: 'Warwick Castle',
    date: 'Weekends in June',
    time: '11am-5pm',
    price: '£28',
    tags: ['family', 'museums', 'sports'],
    city: 'warwick',
    blurb: 'Jousting, falconry, fireworks.',
    why: 'A whole-day with kids.',
  },

  // ===== SHROPSHIRE =====
  {
    title: 'Theatre Severn — touring production',
    venue: 'Theatre Severn, Shrewsbury',
    date: 'Throughout June',
    time: '7.30pm',
    price: 'from £18',
    tags: ['theatre'],
    city: 'shropshire',
    blurb: 'Regional touring rep.',
    why: 'Solid programming.',
  },
  {
    title: 'Shropshire Hills walking',
    venue: 'Long Mynd, Shropshire',
    date: 'Any day',
    time: 'Dawn to dusk',
    price: 'Free',
    tags: ['walking', 'community'],
    city: 'shropshire',
    blurb: 'AONB heath and ridge walks.',
    why: 'Hills proper, not pretend.',
  },
  {
    title: 'Ironbridge Gorge Museums',
    venue: 'Ironbridge, Telford',
    date: 'Throughout June',
    time: '10am-5pm',
    price: '£32 passport',
    tags: ['museums', 'family', 'walking'],
    city: 'telford',
    blurb: 'Ten museums, UNESCO site.',
    why: 'Worth at least a full day.',
  },

  // ===== HEREFORDSHIRE =====
  {
    title: 'Hay Festival (nearby)',
    venue: 'Hay-on-Wye (just over border)',
    date: 'Through 1 June',
    time: 'All day',
    price: 'from £15',
    tags: ['books', 'poetry', 'community'],
    city: 'herefordshire',
    blurb: 'World-class literary festival.',
    why: 'Still time for the closing days.',
  },
  {
    title: 'Black Mountains walks',
    venue: 'Herefordshire-Welsh border',
    date: 'Any day',
    time: 'Dawn to dusk',
    price: 'Free',
    tags: ['walking', 'community'],
    city: 'herefordshire',
    blurb: 'Ridge walks, big skies.',
    why: 'Proper walking country.',
  },

  // ===== STAFFORDSHIRE =====
  {
    title: 'Lichfield Festival',
    venue: 'Lichfield Cathedral & city',
    date: 'Late June onwards',
    time: 'Various',
    price: 'Various',
    tags: ['classical', 'community', 'art'],
    city: 'lichfield',
    blurb: 'Annual arts festival, cathedral-led.',
    why: 'One of the better small festivals.',
  },
  {
    title: 'Cannock Chase mountain biking',
    venue: 'Cannock Chase Forest',
    date: 'Any day',
    time: 'Daylight',
    price: 'Free (trails)',
    tags: ['cycling', 'walking', 'family'],
    city: 'cannockchase',
    blurb: 'Forest trails, all levels.',
    why: 'Best bike trails in region.',
  },
  {
    title: 'Trentham Gardens',
    venue: 'Trentham, Stoke-on-Trent',
    date: 'Throughout June',
    time: '9am-6pm',
    price: '£14',
    tags: ['walking', 'family', 'art'],
    city: 'stoke',
    blurb: 'Italian gardens, monkey forest.',
    why: 'A proper day out.',
  },

  // ===== WARWICKSHIRE =====
  {
    title: 'Ultimate Rave Bingo',
    venue: 'Tamworth',
    date: 'Sat 20 June',
    time: '7pm',
    price: '£18',
    tags: ['dnb', 'comedy'],
    city: 'tamworth',
    blurb: 'Bingo + 90s rave hits.',
    why: 'Genuinely funny chaos.',
  },
  {
    title: 'Nuneaton Saturday market',
    venue: 'Nuneaton town centre',
    date: 'Saturdays',
    time: '9am-4pm',
    price: 'Free',
    tags: ['markets', 'food'],
    city: 'nuneaton',
    blurb: 'Long-running town market.',
    why: 'Local, not a tourist thing.',
  },

  // ===== WORCESTERSHIRE =====
  {
    title: 'Redditch Folk Club',
    venue: 'Redditch',
    date: 'Fri 13 June',
    time: '8pm',
    price: '£6',
    tags: ['folk'],
    city: 'redditch',
    blurb: 'Back-room folk club.',
    why: 'Local folk circuit, still going.',
  },
  {
    title: 'Bromsgrove parkrun',
    venue: 'Sanders Park, Bromsgrove',
    date: 'Saturdays',
    time: '9am',
    price: 'Free',
    tags: ['running', 'community', 'family'],
    city: 'bromsgrove',
    blurb: 'Free 5k, park course.',
    why: 'Just turn up.',
  },
  {
    title: 'Malvern Hills walking',
    venue: 'Malvern Hills, Worcestershire',
    date: 'Any day',
    time: 'Dawn to dusk',
    price: 'Free',
    tags: ['walking', 'community'],
    city: 'malvernhills',
    blurb: 'Ridge walk, panoramic views.',
    why: 'The classic Midlands walk.',
  },
];
